from pathlib import Path
from datetime import datetime
from typing import Dict, Any

from strands import tool


OUTPUT_DIR = Path("outputs")
OUTPUT_DIR.mkdir(exist_ok=True)


@tool
def create_mission_deliverable(
    mission_objective: str,
    completed_tasks: list[str],
) -> Dict[str, Any]:
    """
    Create a real Markdown deliverable documenting the mission work completed.
    """

    if not mission_objective.strip():
        raise ValueError("Mission objective is required.")

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    content = f"""# UNISERVE Mission Deliverable

## Objective

{mission_objective}

## Completed Tasks

"""

    for number, task in enumerate(completed_tasks, 1):
        content += f"{number}. {task}\n"

    content += f"""
## Execution Record

Generated by UNISERVE.

Timestamp: {timestamp}

## Verification

The deliverable was generated locally by the UNISERVE operations agent.
"""

    filename = OUTPUT_DIR / "mission_deliverable.md"
    filename.write_text(content, encoding="utf-8")

    return {
        "success": True,
        "artifact": str(filename),
        "tasks_documented": len(completed_tasks),
        "message": "Mission deliverable created successfully.",
    }


@tool
def verify_mission_deliverable() -> Dict[str, Any]:
    """Verify that the UNISERVE mission deliverable exists and contains data."""

    filename = OUTPUT_DIR / "mission_deliverable.md"

    if not filename.exists():
        return {
            "verified": False,
            "reason": "Mission deliverable does not exist.",
        }

    size = filename.stat().st_size

    return {
        "verified": size > 0,
        "artifact": str(filename),
        "size_bytes": size,
    }
